Product page
Kaidz3n/fake-burrberry-frontend pull request #1
Opened 2017-08-02 07:05 UTC by Kaidz3n

2017-08-02 11:02 UTC, evgenyrodionov commented
https://rawgit.com/Kaidz3n/fake-burrberry-frontend/product-page/index.html

2017-08-02 11:04 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28871028-4f317cbc-778b-11e7-8452-818574fcd88d.png)
![image](https://user-images.githubusercontent.com/775692/28871032-56b81a68-778b-11e7-9e89-6ac7c8505de5.png)
![image](https://user-images.githubusercontent.com/775692/28871043-60592044-778b-11e7-9eca-522fbf3c4e31.png)
![image](https://user-images.githubusercontent.com/775692/28871049-69e99f3a-778b-11e7-8cae-448a717c14f2.png)

2017-08-02 18:44 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28889086-91192f36-77cb-11e7-87f3-9d1c94400db7.png)
![image](https://user-images.githubusercontent.com/775692/28889122-b0460596-77cb-11e7-8a2c-d62164459d01.png)

2017-08-02 18:49 UTC, imevro requested changes
в целом приятно

2017-08-02 18:49 UTC, evgenyrodionov commented on index.html
> +          Coat length: 98cm/38.6in. This is based on
это список параметров

2017-08-02 18:49 UTC, evgenyrodionov commented on index.html
> +          A refined car coat crafted in protective cotton gabardine.<br>
с сервера приходят параграфы, не бры

2017-08-02 18:49 UTC, evgenyrodionov commented on index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
нормалайз выше должен быть

2017-08-02 18:49 UTC, evgenyrodionov commented on index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
иначе будет перебивать твои стили

2017-08-02 18:49 UTC, evgenyrodionov commented on index.html
> +    <div class="container-product-title">
а зачем тут див

2017-08-02 18:49 UTC, evgenyrodionov commented on index.html
> +    <div class="container-product-images">
а зачем контейнер префикс?

2017-08-02 18:49 UTC, evgenyrodionov commented on index.html
> +      <div class="product-information"
у тебя тут тег не закрыт

2017-08-02 18:49 UTC, evgenyrodionov commented on index.html
> +        <button class="product-information-colour-button button-bg-black"></button>
цвета можно через style вешать

2017-08-02 18:49 UTC, evgenyrodionov commented on index.html
> +        <img class="product-description-arrow" src="images/triangle-up.svg">
это лучше делать через цсс чтобы не засорять разметку

2017-08-02 18:49 UTC, evgenyrodionov commented on index.html
> +      <div class="product-description-title">
почему не кнопка?

2017-08-02 18:49 UTC, evgenyrodionov commented on index.html
> +      <button class="footer-button-1">Shipping country: Russian Federation</button>
плохой нейминг когда тебе приходится делать -1

2017-08-03 20:13 UTC, Kaidz3n commented
Все комментарии твои вроде бы учел,исправил. Больше 30 часов убил на это за 3 дня предыдущих, вроде уже начал разбираться, но не совсем. Не нравился все равно нейминг и дивы лишние были,разбивка по блокам не совсем нравилась, + не понимал до конца особенности марджинов/паддингов и line-height, нелогично их использовал. И когда вносил поправку в один блок,все съезжало,не мог разобраться. В итоге решил переписать все, посмотрел много других ПРов, которые ты хвалил, и в итоге и код полностью отрефакторил, и нейминг изменил на более логичный, узнал новые фишки,  после этого много игрался с разными значениями в css, чтобы получше разобраться и  наконец стал более менее понимать все вроде бы))

2017-08-04 08:45 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28961254-56af2e00-790a-11e7-95de-fbdd83d477e2.png)

2017-08-04 08:48 UTC, imevro requested changes
- a11y
- Списки не для списков
- пиксели вместо ремов

2017-08-04 08:48 UTC, evgenyrodionov commented on index.html
> +    <hr>
лучше сделай через бордер  у хедера

2017-08-04 08:48 UTC, evgenyrodionov commented on index.html
> +          <p class="product-recommended-name">Leather Wingtip Check</p>
это заголовки

2017-08-04 13:54 UTC, imevro requested changes

2017-08-04 13:54 UTC, evgenyrodionov commented on index.html
> +          <p class="product-recommended-name">Leather Wingtip Check</p>
Это заголовки!

2017-08-04 18:03 UTC, imevro requested changes

2017-08-04 18:03 UTC, evgenyrodionov commented on index.html
> +        <li class="product-recommended-more-item" href="https://ru.burberry.com/mens-trench-coats/black/"><a>Men’s Black Trench Coats</a></li>
бтв это не списки

2017-08-04 18:03 UTC, evgenyrodionov commented
делай планшет после фикса

2017-08-05 18:00 UTC, evgenyrodionov commented
Страница слишком широкая, в контейнер засунь её

![image](https://user-images.githubusercontent.com/775692/28997591-1dd7e578-7a21-11e7-8120-640871283efb.png)

2017-08-05 18:03 UTC, imevro requested changes

2017-08-05 18:03 UTC, evgenyrodionov commented on css/style.css
> +  .description-pane-closed:after {
селекторы можно через запятую писать

2017-08-05 18:03 UTC, evgenyrodionov commented on index.html
> +              <a class="footer-info-link" href="https://ru.burberry.com/customer-service/contact-us/">Contact Us</a>
обери в нав

2017-08-06 08:30 UTC, imevro approved these changes

2017-08-06 08:30 UTC, merged

2017-08-06 08:31 UTC, evgenyrodionov commented
Переключаешься в мастер, делаешь гит пулл --ребейз ориджин мастер, новые бранчи от этого нового мастера