Product page react
Kaidz3n/fake-burrberry-frontend pull request #3
Opened 2017-08-10 16:08 UTC by Kaidz3n

2017-08-10 17:29 UTC, imevro requested changes

2017-08-10 17:29 UTC, evgenyrodionov commented on public/manifest.json
> +  "name": "Create React App Sample",
мусор

2017-08-10 17:29 UTC, evgenyrodionov commented on src/Product/Index.jsx
> +        <Description title="Description">
wtf

2017-08-10 17:29 UTC, evgenyrodionov commented on src/Product/Recommendations.jsx
> +            price="120 000 руб."
цену можно числом передавать

2017-08-10 17:29 UTC, evgenyrodionov commented on src/Product/ShippingDescription.jsx
> +class ShippingDescription extends Description {
давай без этого

2017-08-10 22:18 UTC, imevro requested changes
а зачем у тебя два индекса в продакт?

2017-08-10 22:18 UTC, evgenyrodionov commented on src/Product/Card.jsx
> +let NumberFormat = require("react-number-format");
почему не импортом?

2017-08-10 22:18 UTC, evgenyrodionov commented on src/Product/Card.jsx
> +          displayType={"text"}
={""} → =""

2017-08-10 22:18 UTC, evgenyrodionov commented on src/Product/Delivery.jsx
> +  margin-left: .5rem !important;
почему импортанты? выглядит как костыль

2017-08-10 22:18 UTC, evgenyrodionov commented on src/Product/ShippingDescription.jsx
> +      <Icon alt="icon" src={triangleIcon} />
зачем иконку в разметку

2017-08-11 06:32 UTC, Kaidz3n commented
Не знаю, что за глюк с 2 индексами в продакте, у меня один. [http://pastenow.ru/89edbb8fe2adf47f4c95e400761d89a0](url)
[http://pastenow.ru/e98b76e91df9f565a67320591ccf2ff8](url)

2017-08-11 11:01 UTC, evgenyrodionov commented
Это не глюк, это переименование. Гугли как переименовать файл в гите

2017-08-11 11:07 UTC, imevro requested changes

2017-08-11 11:07 UTC, evgenyrodionov commented on src/Product/ColorButton.jsx
> +  return <Button color={props.Value} active={props.active} type="button" />;
поч Value с большой буквы

2017-08-11 11:07 UTC, evgenyrodionov commented on src/Product/ColorButton.jsx
> +  return <Button color={props.Value} active={props.active} type="button" />;
а также что мешает сразу экспортить стайлед-компонент? ради type="button" делать прокладку?

2017-08-11 11:07 UTC, evgenyrodionov commented on src/Product/Delivery.jsx
> +  @media only screen and (max-width: 47.99rem) {
что за значение странное

2017-08-11 13:57 UTC, Kaidz3n commented
Удалил лишний index

2017-08-11 18:06 UTC, imevro requested changes
в целом нормально, но поставь преттир

2017-08-11 18:06 UTC, evgenyrodionov commented on src/Footer/Navigation.jsx
> +export default function() {
поставь преттир

2017-08-11 18:06 UTC, evgenyrodionov commented on src/Header/Index.jsx
> +import React from "react";
этот Индекс.джсх тоже лишний

2017-08-12 18:08 UTC, imevro requested changes

2017-08-12 18:08 UTC, evgenyrodionov commented on package.json
> +    "prettier": "^1.5.3"
нет, его нужно ставить плагином в редактор

2017-08-12 18:08 UTC, evgenyrodionov commented on src/Common/responsive.jsx
> +  <Responsive minWidth={992} children={children} />;
чилдрен это не проп (телеграф)

2017-08-12 18:08 UTC, evgenyrodionov commented on src/Header/index.jsx
> +    height: 16px;
а тут почему не ремы

2017-08-12 18:08 UTC, evgenyrodionov commented on src/Header/index.jsx
> +    width: 100%;
зачем ширина

2017-08-12 18:08 UTC, evgenyrodionov commented on src/Header/index.jsx
>    width: 138px;
зачем ширина

2017-08-12 18:08 UTC, evgenyrodionov commented on src/Product/Delivery.jsx
> +  margin-left: -1rem;
что за костыль

2017-08-12 18:08 UTC, evgenyrodionov commented on src/Product/GalleryImages.jsx
> +  & > *:nth-child(2) {
никогда не используй *

2017-08-12 18:08 UTC, evgenyrodionov commented on src/Product/Information.jsx
> +import SizeButton from "./SizeButton.jsx";
зачем жсх

2017-08-12 18:08 UTC, evgenyrodionov commented on src/Product/Information.jsx
> +import SizeButton from "./SizeButton.jsx";
в импорте

2017-08-12 18:08 UTC, evgenyrodionov commented on src/Product/Information.jsx
> +      <Large>
вот то что ты по сути дублируешь всю страницу — нихуя не круто. Нужно только различающиеся части типа кнопки `Need size help?`

2017-08-12 18:08 UTC, evgenyrodionov commented on src/Product/Information.jsx
> +      <Large>
а ты пошел по пути наименьшего сопротивления и всю страницу ебанул дважды

2017-08-12 18:08 UTC, evgenyrodionov commented on src/Product/SizeButton.jsx
> +    <SizeButton type="button">
зачем эта прокладка? сразу экспорти ск

2017-08-13 06:41 UTC, Kaidz3n commented
Постарался все замечания учесть. Единственное, по поводу [<img src="https://i.paste.pics/1XPYR.png" width="644" height="289" alt="Screenshot">](url) физически не успел переделать. Понял свою ошибку, что сделал лишнюю работу.У себя уже разбил на более мелкие компоненты и переделываю в нормальный вид без дублирования. Если остальное устроит и пропустишь дальше, обещаю к старту 3 недели ( 12 утра понедельника) этот момент переделать и загрузить нормальную версию.

2017-08-13 11:28 UTC, evgenyrodionov commented
Переделай

2017-08-13 11:30 UTC, imevro requested changes
как исправишь всё — в телеграм напиши

2017-08-13 11:30 UTC, evgenyrodionov commented on src/Common/responsive.jsx
> +export const XS_MD = ({ children }) =>
плохой нейминг, PascalCase не так выглядит

2017-08-13 11:30 UTC, evgenyrodionov commented on src/Product/Delivery.jsx
> +  margin-left: -1rem;
и?

2017-08-14 10:31 UTC, imevro approved these changes

2017-08-14 10:33 UTC, merged